export const UPDATE_PROJECT = "PROJECT/UPDATE_PROJECT";
export const SAVE_PROJECT = "PROJECT/SAVE_PROJECT";
export const DELETE_PROJECT = "PROJECT/DELETE_PROJECT";
export const FETCHED_ALL_PROJECTS = "PROJECT/FETCHED_PROJECTS";
export const FETCHED_PROJECT = "PROJECT/FETCHED_PROJECT";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
